add new color options, auto prefix color on 2 params to emiters, add die() and MsgFatal() fix edge-case on ssh agent

diff --git a/dotfiles/blib b/dotfiles/blib
--- a/dotfiles/blib
+++ b/dotfiles/blib
@@ -12,20 +12,44 @@
 
 # these exports possibly redundant to .profile, but needed here for sudo...
 export BLACK='\u001b[30m'
-export BLUE='\033[01;34m'
-export CYAN='\033[01;36m'
-export GREEN='\033[01;32m'
-export MAGENTA='\033[01;35m'
-export RED='\033[0;31m'
-export YELLOW='\033[0;33m'
-export WHITE='\033[01;37m'
 export RESET='\033[00m'
+
+export BLUE='\033[0;94m'
+export CYAN='\033[0;96m'
+export GREEN='\033[0;92m'
+export MAGENTA='\033[0;95m'
+export RED='\033[0;91m'
+export YELLOW='\033[0;93m'
+export WHITE='\033[0;97m'
+
+export B_BLUE='\033[1;34m'
+export B_CYAN='\033[1;36m'
+export B_GREEN='\033[1;32m'
+export B_MAGENTA='\033[1;35m'
+export B_RED='\033[1;31m'
+export B_YELLOW='\033[1;33m'
+export B_WHITE='\033[1;37m'
+
+export BG_BLUE='\033[01;44m'
+export BG_CYAN='\033[01;46m'
+export BG_GREEN='\033[01;42m'
+export BG_MAGENTA='\033[01;45m'
+export BG_RED='\033[0;41m'
+export BG_YELLOW='\033[0;43m'
+export BG_WHITE='\033[01;47m'
 
 function emit() { echo ">> $@" >&2 ; }
 
-function emitC() { if [[ "$1" == "-" ]]; then shift; nl=''; else nl="\n"; fi; color=${1^^}; shift; q="$@"; printf "${!color}${q}${RESET}${nl}" >&2 ; }
+function emitC() {
+    if [[ "$1" == "-" ]]; then shift; nl=''; else nl="\n"; fi;
+    color=${1^^}; shift; cnt="$#"; q="$@"
+    if [[ "$cnt" == "2" ]];
+        then echo -ne "${!color}$1${RESET} $2${nl}" >&2
+        else echo -ne "${!color}$q${RESET}${nl}" >&2
+    fi
+}
 
-function emitc() { color=${1^^}; shift; if [[ -t 1 ]]; then emitC "$color" "$@"; else printf "$@\n" >&2; fi ; }
+function emitc() { color=${1^^}; shift; q="$@"; if [[ -t 1 ]]; then emitC "$color" "$@"; else echo "$q" >&2; fi ; }
 
 function ColorLines() {
     colr="$1"
@@ -38,7 +62,7 @@ function ColorLines() {
 }
 
 
-# ==================== thigns that depend on colorizers...
+# ==================== things that depend on colorizers...
 
 
 # ---- HiLight stdErr
@@ -63,6 +87,14 @@ function erun() {
 }
 
 
+# ---- fatal exit
+
+function die() {
+    code=9; if [[ $1 =~ ^[0-9]+$ ]]; then code="$1"; shift; fi
+    emitc red "FATAL: " "$@"
+    exit $code
+}
+
 # ---- send message to stdout/stderr if terminal, otherwise via zenity
 
 function Msg() {
@@ -77,9 +109,9 @@ function Msg() {
 	else                                   echo "$msg"
 	fi
     else
-	if [[ "$type" == "warn"* ]]; then  /usr/bin/zenity --warning --timeout $timeout --text "$msg" &
-	elif [[ "$type" == "err"* ]]; then /usr/bin/zenity --error --timeout $timeout --text "$msg" &
-	else                               /usr/bin/zenity --info --timeout $timeout --text "$msg" &
+	if   [[ "$type" == "warn"* ]]; then /usr/bin/zenity --warning --timeout $timeout --text "$msg" &
+	elif [[ "$type" == "err"* ]];  then /usr/bin/zenity --error   --timeout $timeout --text "$msg" &
+	else                                /usr/bin/zenity --info    --timeout $timeout --text "$msg" &
 	fi
     fi
 }
@@ -89,3 +121,4 @@ function MsgWarn()     { type="warn"              Msg "$@"; }
 function MsgWarning()  { type="warn"              Msg "$@"; }
 function MsgErr()      { type="error" timeout="0" Msg "$@"; }
 function MsgError()    { type="error" timeout="0" Msg "$@"; }
+function MsgFatal()    { type="error" timeout="0" Msg "$@"; exit 9; }
