add servarica config

diff --git a/containers/rclonedock/files/etc/init b/containers/rclonedock/files/etc/init
--- a/containers/rclonedock/files/etc/init
+++ b/containers/rclonedock/files/etc/init
@@ -128,7 +128,7 @@ case $MODE in
 	STATUS=$?
 	if [[ $STATUS != 0 ]]; then echo "rclone $MODE exited with status $STATUS"; exit $STATUS; fi
         ;;
-    
+
     test)
 	# Docker "Test" script will have already created unique content for the test-out file.
 	SRC="/root/echo-back/test-out"
@@ -146,6 +146,27 @@ case $MODE in
 	echo "init: pass"
 	sleep 3  # hang around long enough for the test to find the container metadata.
 	;;
+
+    servarica)
+	# fix ownership of ~/.ssh (was set to shifted uids during copy which used alt uid namespace)
+	chown -R root:root /root/.ssh
+	# using rsync rather than rclone, so re-specialize our run flags
+	if [[ "$VERBOSE" == "1" ]]; then STATS='-vP --stats'; else STATS='--stats'; fi
+
+	# check that source is mounted ok (dont want to zap dest because of a src mounting error).
+	if [[ ! -d /root/src/rw ]]; then echo "rclone $MODE cannot find source canary file; aborting."; exit -2; fi
+	# copy rsnap daily.0 to remote archive
+	rsync ${STATS} -ah --one-file-system --acls --xattrs --del /root/src servarica:/home/backup
+	STATUS=$?
+	if [[ $STATUS != 0 ]]; then echo "rclone $MODE exited with status $STATUS"; exit $STATUS; fi
+
+	# Sanity check: copy jack's cron log back into a holding area.  filewatchdock also monitors the age of this file.
+	DEST="/root/echo-back/ken-touch-servarica"
+	echo "$(date): starting echo back to ${DEST}"
+	rm -rf ${DEST}
+	rsync servarica:/home/backup/src/home/home/ken/share/tmp/touch ${DEST}
+	/usr/bin/diff /root/src/home/home/ken/share/tmp/touch ${DEST} || { echo "ERROR- jack cron copy-back doesnt match."; exit -4; }
+        ;;
 
     wasabi)
 	# check that source is mounted ok (dont want to zap dest because of a src mounting error).
